### ISSUE TITLE
Notebook for Influential Data Identification

### ISSUE THREAD

**Issue by ajsanjoaquin** [ykwon0407/DataInf#1]
Hello, can you please release a demo notebook for your influential data identification task? Thank you.

EDIT: Congrats! This is just a minor issue, so please don't let me distract you from your time.  :)

**Comment by ykwon0407** [comment]
@ajsanjoaquin Thank you so much for your interest in our paper!! I will definitely add them very soon. (There have been personal things to handle (new baby), and I haven't updated this repo these days. Sorry!) I will keep open this issue!

**Comment by ykwon0407** [comment]
@ajsanjoaquin Thank you again for bringing up this issue. I just updated our repo, providing two Jupyter notebooks for the influential data identification tasks. Please find `READMD.md` and `notebooks`. I will close this issue but will keep this repo updated to include sentence transformation and text-to-image generation tasks.
