### ISSUE TITLE
Influence computation code and time for SD1.5

### ISSUE THREAD

**Issue by Buhua-Liu** [ykwon0407/DataInf#4]
Hi! Interesting work! Could you please share the code for computing data influence on the stable diffusion model? BTW, how long it take to compute the influence for SD1.5?

**Comment by ykwon0407** [comment]
Hi @Buhua-Liu, text-to-image experiments will be updated soon. I don't remember the exact number, but it takes less than 5 hours to fine-tune the SD1.5 model (with one A40 GPU) and another 1~2 hours to compute influences (around a thousand of samples).

**Comment by ykwon0407** [comment]
Hi @Buhua-Liu, thank you so much for your patience. We've finally uploaded the text-to-image Jupyter Notebook at [this link](notebooks/Influential_Data_Identification-Stable_Diffusion-Style_Transfer.ipynb).
